# Config file for Stage 1 - Data Entry

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage01_data_entry'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'spiking_hippocampus'

# Name of stage output file.
STAGE_OUTPUT: 'data'

# File format in which all intermediate neo objects are stored
NEO_FORMAT: 'nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    spiking_hippocampus: '/path/to/WK_DIR/hands_on_cobrawap/test_datasets/spiking_hippocampus/data/active_channels_100mm_10ms_traces.npy'

CURATION_SCRIPT: '/path/to/WK_DIR/hands_on_cobrawap/test_datasets/spiking_hippocampus/profiles/stage01_data_entry/scripts/curate.py'

# pixel size
SPATIAL_SCALE: 0.1  # mm

SAMPLING_RATE: 0.1  # KHz

# time slice in s
# if None, the entire recording is used
T_START: 0.5
T_STOP: 20.0

# 2D plane on which 3D data has been projected
PROJECTION: 'Y-Z'

# Metadata
ANNOTATIONS:
    experimental_lab: 'M. Migliore lab CNR-IBF Palermo'
    technique: 'Hippocampus spiking simulations'
    # doi: 10.25493/QFZK-FXS
    # model_type: 'WT'
ARRAY_ANNOTATIONS:
    x_coords: 'None'
    y_coords: 'None'
ARRAY_ANNOTATION_FILE: '/path/to/WK_DIR/hands_on_cobrawap/test_datasets/spiking_hippocampus/data/active_channels_100mm_10ms_coords.npy'

KWARGS: 'None'

# Plot settings
PLOT_TSTART: 'None'  # float (in s) or 'None'.
PLOT_TSTOP: 'None'  # float (in s) or 'None'.
PLOT_CHANNELS: [221]  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: 'png'
