# Config file for Stage 1 - Data Entry

# Name of stage, must be identical with folder name
STAGE_NAME: "stage01_data_entry"

# The profile name is the key for this parameter configuration.
# Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: "imaging_deep_anesthesia"

# Name of stage output file.
STAGE_OUTPUT: "data"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: "nix"

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: False

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    imaging_deep_anesthesia: "/path/to/WK_DIR/hands_on_cobrawap/test_datasets/imaging_deep_anesthesia/data"

CURATION_SCRIPT: "curation_script.py"

# pixel size
SPATIAL_SCALE: 0.05  # mm

SAMPLING_RATE: 25  # Hz

# time slice in s
# if None, the entire recording is used
T_START: None
T_STOP: None

# recommend top: ventral
ORIENTATION_TOP: "ventral"
# recommended right: "lateral" for right hemisphere, "medial" for left hemisphere
ORIENTATION_RIGHT: "lateral"

# Metadata
ANNOTATIONS:
    technique: "calcium imaging"
    doi: "10.25493/QFZK-FXS"
    anesthetic: "ketamine-xylazine"
    concentration: "100 & 10 mg/kg"
    model_type: "WT"

ARRAY_ANNOTATIONS: "None"

KWARGS: "None"

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [4040, 5050, 6060]  # int, list of ints, or "None" (default) -> picks channel by random
PLOT_FORMAT: "png"
