# Config file for Stage 5 - Wave Characterization

# Name of stage, must be identical with folder name
STAGE_NAME: "stage05_wave_characterization"

# The profile name is the key for this parameter configuration.
# Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: "imaging_deep_anesthesia"

# Name of the output file
STAGE_OUTPUT: "wavefronts_wave-wise_measures.csv"

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: ["None", "None", "None"]   # int or None. default "None" -> randomly selected
PLOT_FORMAT: "png"

# Wave event name
# "wavefronts", "wavemodes"
EVENT_NAME: "wavefronts"

# Measures to compute
# "label_planar", "velocity_planar", "direction_planar", "inter_wave_interval",
# "time_stamp", "duration", "number_of_triggers", "annotations"
MEASURES: ["annotations", "duration", "number_of_triggers", "inter_wave_interval",
           "label_planar", "velocity_planar", "direction_planar", "time_stamp"]

# Label Planar
##############
ALIGNMENT_THRESHOLD: 0.9

# Direction Planar
##################
# "trigger_interpolation", "optical_flow"
DIRECTION_METHOD: "optical_flow"

# Time Stamp
############
# "start", "middle", "end"
TIME_STAMP_POINT: "start"

# Annotations
#############
# Use include_keys, if they are empty apply ignore_keys
INCLUDE_KEYS: ["wavemode", "spatial_scale", "anesthetic", "concentration",
               "doi", "disease_model", "model_type", "technique",
               "macro_pixel_dim"]
IGNORE_KEYS: ["cluster_algorithm", "cluster_eps", "cluster_metric",
              "cluster_min_samples", "threshold", "experimental_lab",
              "psd_freq_res", "psd_overlap", "psd_fs"]
