STAGES:
    - "stage01_data_entry"
    - "stage02_processing"
    - "stage03_trigger_detection"
    - "stage04_wave_detection"
    - "stage05_wave_characterization"
    # - "stage05_channel_wave_characterization"

# A profile collects the parameter configuration for a specific dataset.
# The stages are executed using the config_<PROFILE>.yaml file, and results are stored in output_path/<PROFILE>/
PROFILE: "imaging_deep_anesthesia"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: "nix"

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
# PLOT_TSTART: 0  # in s
# PLOT_TSTOP: 10  # in s
# PLOT_CHANNELS: ["2011", "3022", "4030"]  # int or None. default "None" -> randomly selected
PLOT_FORMAT: "png"

# VIDEO SETTINGS
################
QUALITY: 5 # 0(good) - 31(bad)
SCALE_X: 720
SCALE_Y: 720
FPS: 18
BITRATE: 20M
# displayed sampling rate, the data will be stretched or compressed to.
# If None, the inherent sampling rate is used.
FRAME_RATE: None
# "gray", "viridis" (sequential), "coolwarm" (diverging), "twilight" (cyclic)
COLORMAP: "twilight"
PLOT_EVENT: "wavefronts" # name of neo event to plot ("transitions", "wavefronts"), default is None
MARKER_COLOR: "r"
